FROM public.ecr.aws/docker/library/golang:1.24 AS build-image
WORKDIR /src
COPY . .
RUN GOOS=linux GOARCH=arm64 BATON_LAMBDA_SUPPORT=1 make build
FROM public.ecr.aws/lambda/provided:al2023
COPY --from=build-image /src/dist/linux_arm64/baton-okta .
ENTRYPOINT ["./baton-okta", "lambda"]
